# Generated by Django 6.1 on 2026-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Exposure', models.FloatField()),
                ('VehPower', models.IntegerField()),
                ('VehAge', models.IntegerField()),
                ('DrivAge', models.IntegerField()),
                ('BonusMalus', models.IntegerField()),
                ('VehBrand', models.CharField(max_length=10)),
                ('VehGas', models.CharField(max_length=20)),
                ('Area', models.CharField(max_length=5)),
                ('Density', models.IntegerField()),
                ('Region', models.CharField(max_length=50)),
                ('prediction', models.CharField(max_length=20)),
                ('claim_probability', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
            ],
        ),
    ]
